/**
 * 與 mahjong-arch colyseus-v2-server `v2TaiPatternCatalog` 機械 id 對齊（供後台 UI）。
 * opening / draw：已接演算者為 true；部分 event_* 僅作摸牌「情境閘門」或開局粗估。
 */
export const V2_BIAS_PATTERN_OPTIONS: Array<{
  id: string
  label: string
  opening: boolean
  draw: boolean
  northernOnly: boolean
  southernOnly: boolean
}> = [
  {
    id: 'opening_tenpai',
    label: '起手聽牌（天聽／地聽前置）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_qing_yi_se',
    label: '清一色（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_hun_yi_se',
    label: '混一色（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_zi_yi_se',
    label: '字一色（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_peng_peng_hu',
    label: '碰碰胡（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_xiao_san_yuan',
    label: '小三元（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_da_san_yuan',
    label: '大三元（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_xiao_si_xi',
    label: '小四喜（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_da_si_xi',
    label: '大四喜（骨架）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_dragon_triplet_any',
    label: '三元台（前置：至少一刻三元）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_wind_triplet_any',
    label: '風牌刻（前置：至少一圈風刻）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_triplet_groups_ge_3',
    label: '三暗坎（粗估：手牌≥3 組刻子面）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_triplet_groups_ge_4',
    label: '四暗坎（粗估：手牌≥4 組刻子面）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_triplet_groups_ge_5',
    label: '五暗坎（粗估：手牌≥5 組刻子面）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_ping_hu_all_simple',
    label: '平胡傾向（無字、皆數牌）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_li_gu_candidate',
    label: '嚦咕嚦咕（可成形）',
    opening: true,
    draw: false,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'shape_north_ba_xian_flowers',
    label: '八仙過海（花牌≥8）',
    opening: true,
    draw: false,
    northernOnly: true,
    southernOnly: false,
  },
  {
    id: 'shape_north_hua_gang',
    label: '花槓（四季或四君子齊）',
    opening: true,
    draw: false,
    northernOnly: true,
    southernOnly: false,
  },
  {
    id: 'draw_normal_turn',
    label: '僅一般輪摸牌（不含槓後補牌）',
    opening: false,
    draw: true,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'draw_winning_tile',
    label: '下一張可胡（標準胡，不限摸牌情境）',
    opening: false,
    draw: true,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'draw_after_kong',
    label: '槓後補牌可胡（槓上開花情境）',
    opening: false,
    draw: true,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'draw_hai_di',
    label: '海底最後一張可胡（海底撈月情境）',
    opening: false,
    draw: true,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'draw_men_qing_hu',
    label: '門清時下一張可胡',
    opening: false,
    draw: true,
    northernOnly: false,
    southernOnly: false,
  },
  {
    id: 'draw_du_ting_hu',
    label: '獨聽時下一張可胡',
    opening: false,
    draw: true,
    northernOnly: false,
    southernOnly: false,
  },
  { id: 'event_zhuang', label: '莊家', opening: false, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_lian_zhuang', label: '連N拉N', opening: false, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_men_qing', label: '門清（摸牌閘門）', opening: false, draw: true, northernOnly: false, southernOnly: false },
  {
    id: 'event_men_qing_zi_mo',
    label: '門清自摸（摸牌閘門，同門清可胡）',
    opening: false,
    draw: true,
    northernOnly: false,
    southernOnly: false,
  },
  { id: 'event_zi_mo', label: '自摸（摸牌閘門）', opening: false, draw: true, northernOnly: false, southernOnly: false },
  { id: 'event_du_ting', label: '獨聽（開局骨架）', opening: true, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_qiang_gang', label: '搶槓', opening: false, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_yan_pai', label: '眼牌', opening: false, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_gang_shang_kai_hua', label: '槓上開花（摸牌閘門）', opening: false, draw: true, northernOnly: false, southernOnly: false },
  { id: 'event_hai_di_lao_yue', label: '海底撈月（摸牌閘門）', opening: false, draw: true, northernOnly: false, southernOnly: false },
  { id: 'event_hai_di_lao_yu', label: '海底撈魚', opening: false, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_quan_qiu', label: '全求', opening: false, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_tian_ting', label: '天聽（宣告＋序盤）', opening: false, draw: false, northernOnly: false, southernOnly: false },
  { id: 'event_di_ting', label: '地聽（宣告＋序盤）', opening: false, draw: false, northernOnly: false, southernOnly: false },
  {
    id: 'event_hua_pai_north',
    label: '花牌（北部正花計台）',
    opening: false,
    draw: false,
    northernOnly: true,
    southernOnly: false,
  },
  {
    id: 'event_men_feng_tai_north',
    label: '門風台（北部）',
    opening: false,
    draw: false,
    northernOnly: true,
    southernOnly: false,
  },
  {
    id: 'event_quan_feng_tai_north',
    label: '圈風台（北部）',
    opening: false,
    draw: false,
    northernOnly: true,
    southernOnly: false,
  },
  {
    id: 'event_pei_pai_hua_hu',
    label: '配牌花胡（開局花牌≥7 粗估）',
    opening: true,
    draw: false,
    northernOnly: true,
    southernOnly: false,
  },
  {
    id: 'event_qi_qiang_yi',
    label: '七搶一（開局花牌=7 粗估）',
    opening: true,
    draw: false,
    northernOnly: true,
    southernOnly: false,
  },
]
